[target.arm-linux-androideabi]
linker = "armv7a-linux-androideabi21-clang"
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-linux-android]
linker = "aarch64-linux-android21-clang"
rustflags = ["-C", "target-feature=+crt-static"]
